### ISSUE TITLE
列表有误

### ISSUE THREAD

**Issue by sea-co** [dongm2ez/general-db#2]
public function getAllList($params)
    {
        $extends = $this->listParamsFormat($params);
        $input = $this->listFillableFromArray($params, [
            'id',
            'user_id',
            'create_at',
            'update_at',
        ]);

        $result = (new \App\Repositories\ExampleRepository())->getList(array_merge($input, ['_extends' => $extends]));

        return $result;
    }
 这点应该是listFillable FromArray   $this->listFillableFromArray($listFillable, $params);

**Comment by yjk520** [comment]
$input = $this->listFillableFromArray([
            'id',
            'username',
            'created_at',
            'updated_at',
        ],$params);

**Comment by yjk520** [comment]
应该是这样

**Comment by yjk520** [comment]
> public function getAllList($params)
> {
> $extends = $this->listParamsFormat($params);
> $input = $this->listFillableFromArray($params, [
> 'id',
> 'user_id',
> 'create_at',
> 'update_at',
> ]);
> 
> ```
>     $result = (new \App\Repositories\ExampleRepository())->getList(array_merge($input, ['_extends' => $extends]));
> 
>     retur

> public function getAllList($params)
> {
> $extends = $this->listParamsFormat($params);
> $input = $this->listFillableFromArray($params, [
> 'id',
> 'user_id',
> 'create_at',
> 'update_at',
> ]);
> 
> ```
>     $result = (new \App\Repositories\ExampleRepository())->getList(array_merge($input, ['_extends' => $extends]));
> 
>     return $result;
> }
> ```
> 
> 这点应该是listFillable FromArray $this->listFillableFromArray($listFillable, $params);



> public function getAllList($params)
> {
> $extends = $this->listParamsFormat($params);
> $input = $this->listFillableFromArray($params, [
> 'id',
> 'user_id',
> 'create_at',
> 'update_at',
> ]);
> 
> ```
>     $result = (new \App\Repositories\ExampleRepository())->getList(array_merge($input, ['_extends' => $extends]));
> 
>     return $result;
> }
> ```
> 
> 这点应该是listFillable FromArray $this->listFillableFromArray($listFillable, $params);
